<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DriverSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing to avoid duplicates
        DB::table('drivers')->truncate();

        $drivers = [
            [
                'id' => 1,
                'nid' => null,
                'name' => 'Lynn Hensley',
                'email' => 'ponila@mailinator.com',
                'phone' => '+1 (174) 592-3288',
                'nik' => 468,
                'nik_image' => null,
                'sim' => 914,
                'sim_image' => null,
                'password' => '$2y$12$rQ2hd.1YfSUrhvwvCyr6sOpn48lA8UiSJZDARk32/gRzXaEibb71O',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:21:28',
                'updated_at' => '2026-03-27 23:21:28',
            ],
            [
                'id' => 2,
                'nid' => 'siw01',
                'name' => 'Nanankjhe',
                'email' => 'siw01@siwride.com',
                'phone' => '0884942978',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$SWQ87ILqVxWXs3/amyssp.5SsWcyrqLUXnyFUDbICOFj83AJuZCZK',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:31',
                'updated_at' => '2026-03-27 23:39:31',
            ],
            [
                'id' => 3,
                'nid' => 'siw02',
                'name' => 'Rahman',
                'email' => 'siw02@siwride.com',
                'phone' => '0811772370',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$l5Hmm9KihWgEeaoCCL/ujuxkc.Ufji1Vrxfxo/AjOthxATAU/X3wi',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:32',
                'updated_at' => '2026-03-27 23:39:32',
            ],
            [
                'id' => 4,
                'nid' => 'siw03',
                'name' => 'Eko Satrio',
                'email' => 'siw03@siwride.com',
                'phone' => '0853422619',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$jT5dXpqViY/MG2lEriiZmepwr3hJQBDyhLaHSSo8eSMbBXd/iWZUy',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:32',
                'updated_at' => '2026-03-27 23:39:32',
            ],
            [
                'id' => 5,
                'nid' => 'siw04',
                'name' => 'Wawan',
                'email' => 'siw04@siwride.com',
                'phone' => '0834629705',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$foFU0IzrhoVuO0udwm9VN.WvKcmiBRRgAi8GXoLKgY6e6mmlbRdF6',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:32',
                'updated_at' => '2026-03-27 23:39:32',
            ],
            [
                'id' => 6,
                'nid' => 'siw05',
                'name' => 'Arya',
                'email' => 'siw05@siwride.com',
                'phone' => '0811733490',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$9CSKWSzcsgmfTnmxITlPV.2C/HJx.fuy3tDat3oX9fDbI3Q2lOBjW',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:32',
                'updated_at' => '2026-03-27 23:39:32',
            ],
            [
                'id' => 7,
                'nid' => 'siw06',
                'name' => 'Angga',
                'email' => 'siw06@siwride.com',
                'phone' => '0893124119',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$oh78KWDqCJngbyTlNtMPBek3fHPbMNpOX.ar.YrA/yDX3UL4.S.oq',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:33',
                'updated_at' => '2026-03-27 23:39:33',
            ],
            [
                'id' => 8,
                'nid' => 'siw07',
                'name' => 'Joe / Cash',
                'email' => 'siw07@siwride.com',
                'phone' => '0879690194',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$aX9LYid8mex.pmbF9vwIZO1Tz6CyCb.BNd8qctAvjLKLR3AJ9ir/K',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:33',
                'updated_at' => '2026-03-27 23:39:33',
            ],
            [
                'id' => 9,
                'nid' => 'siw08',
                'name' => 'Teddy',
                'email' => 'siw08@siwride.com',
                'phone' => '0826884527',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$R8oqQ92KzXWQNsj6n/J4HO2dLq4f.yQzHjshlC5dVc152afIkC6Qy',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:33',
                'updated_at' => '2026-03-27 23:39:33',
            ],
            [
                'id' => 10,
                'nid' => 'siw09',
                'name' => 'Dimas',
                'email' => 'siw09@siwride.com',
                'phone' => '0817525628',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$z4DM5An9nIDVwTXhO0YtDuGCys7kqXESLVRe9gzvaSw0VBBt3UWLK',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:34',
                'updated_at' => '2026-03-27 23:39:34',
            ],
            [
                'id' => 11,
                'nid' => 'siw10',
                'name' => 'Ardian',
                'email' => 'siw10@siwride.com',
                'phone' => '0843127136',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$qcusZOT4fTK6YO9MWBIL4OTijOc3M89C2.2Zx3CvHS1T0JdTjdKlK',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:34',
                'updated_at' => '2026-03-27 23:39:34',
            ],
            [
                'id' => 12,
                'nid' => 'siw11',
                'name' => 'Zaky',
                'email' => 'siw11@siwride.com',
                'phone' => '0834004335',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$ARWQmgxegeWvLnNv9qkdN.RLKvFnuDT/I2/h8Kjhrwxsi2r1jv3ze',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:34',
                'updated_at' => '2026-03-27 23:39:34',
            ],
            [
                'id' => 13,
                'nid' => 'siw12',
                'name' => 'Wildan',
                'email' => 'siw12@siwride.com',
                'phone' => '0838598608',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$SM0SxivPQbtICCHr4C2ckuDjcqgSLe4NIG9.6aM0.tejCV/4nzPIO',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:34',
                'updated_at' => '2026-03-27 23:39:34',
            ],
            [
                'id' => 14,
                'nid' => 'siw13',
                'name' => 'Nyoman Edy',
                'email' => 'siw13@siwride.com',
                'phone' => '0893087814',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$s0eOfCtKs.WWAveaSSKGW.fDfwP1TkiZjMumuVmmxxVK5/6XOnLae',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:35',
                'updated_at' => '2026-03-27 23:39:35',
            ],
            [
                'id' => 15,
                'nid' => 'siw14',
                'name' => 'Bayu',
                'email' => 'siw14@siwride.com',
                'phone' => '0834113926',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$w7tsxNonWwnF7fOS06ZRGevdMWjt4oM9Bxn0K0FM2L.7j/r5yL.Su',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:35',
                'updated_at' => '2026-03-27 23:39:35',
            ],
            [
                'id' => 16,
                'nid' => 'siw15',
                'name' => 'Yan Tande',
                'email' => 'siw15@siwride.com',
                'phone' => '0874342638',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$HNn20mnqogsYnJdp/upMfeizY0/gWu1s./c6kZWubZITO3Ell2Z3q',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:35',
                'updated_at' => '2026-03-27 23:39:35',
            ],
            [
                'id' => 17,
                'nid' => 'siw16',
                'name' => 'Pak Urip',
                'email' => 'siw16@siwride.com',
                'phone' => '0872981093',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$gvOIJpfsZKkT5aOds9NMuOzsS3tsl9hfP8OSUGQATr6r9hH1mtPhu',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:35',
                'updated_at' => '2026-03-27 23:39:35',
            ],
            [
                'id' => 18,
                'nid' => 'siw17',
                'name' => 'Yayan',
                'email' => 'siw17@siwride.com',
                'phone' => '0837671089',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$y4OwMcnZVVVOCfrYa3LlXeVCrSYoKQSSLBNkhug9/xMNfwyPFw7QW',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:36',
                'updated_at' => '2026-03-27 23:39:36',
            ],
            [
                'id' => 19,
                'nid' => 'siw18',
                'name' => 'Toni',
                'email' => 'siw18@siwride.com',
                'phone' => '0859995515',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$eMig7xJ43mFHyTQrYi1NTu1uEWXskxBjR9faezqAXcgOkXt1RqogC',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:36',
                'updated_at' => '2026-03-27 23:39:36',
            ],
            [
                'id' => 20,
                'nid' => 'siw19',
                'name' => 'Basri',
                'email' => 'siw19@siwride.com',
                'phone' => '0847782627',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$8bzAn7Ah0iFL3yOdCTiyC.E60NPfXYAZJx0EWt2rKUst1d6oAMmdC',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:36',
                'updated_at' => '2026-03-27 23:39:36',
            ],
            [
                'id' => 21,
                'nid' => 'siw20',
                'name' => 'Ivan',
                'email' => 'siw20@siwride.com',
                'phone' => '0844832400',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$IfWoyv7wsahb63dNNkiC8.3Ds350xwQXHlLNi0Jt7A/udRnC6s4Xu',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:37',
                'updated_at' => '2026-03-27 23:39:37',
            ],
            [
                'id' => 22,
                'nid' => 'siw21',
                'name' => 'Anom',
                'email' => 'siw21@siwride.com',
                'phone' => '0819394832',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$MA33f3AZikAKAOIu3saH5exTQrViSWvZGxs8.ZxNmEMShoo8zHcT6',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:37',
                'updated_at' => '2026-03-27 23:39:37',
            ],
            [
                'id' => 23,
                'nid' => 'siw22',
                'name' => 'Lutfi',
                'email' => 'siw22@siwride.com',
                'phone' => '0811903626',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$JPYSF6nRLfJbTNTJn7F.KOX39V0fCk01CyVMwkWDdDXMSdv/ayjCG',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:37',
                'updated_at' => '2026-03-27 23:39:37',
            ],
            [
                'id' => 24,
                'nid' => 'siw23',
                'name' => 'Angga / cash',
                'email' => 'siw23@siwride.com',
                'phone' => '0836753640',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$XHXlxkZaAbkj9jFeTQkOvO5eQa63IxZ9wxxa8JN3RKr7A5YInBsqG',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:37',
                'updated_at' => '2026-03-27 23:39:37',
            ],
            [
                'id' => 25,
                'nid' => 'siw24',
                'name' => 'Driver siw24',
                'email' => 'siw24@siwride.com',
                'phone' => '0883899115',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$0PAy/F.KUzS0Y99.hVTSX.M7TawXQlYsMLsRqU8L8AwswlJUe8qmK',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:38',
                'updated_at' => '2026-03-27 23:39:38',
            ],
            [
                'id' => 26,
                'nid' => 'siw25',
                'name' => 'Sby',
                'email' => 'siw25@siwride.com',
                'phone' => '0880967071',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$B612/gCeCgwrrxvZk1yyEO5kKgpl4kvaq..4Q76k3mtR8GTjGd1uW',
                'image' => null,
                'status' => 'active',
                'created_at' => '2026-03-27 23:39:38',
                'updated_at' => '2026-03-27 23:39:38',
            ],
            [
                'id' => 27,
                'nid' => 'DRV-2218',
                'name' => 'Pak Eko',
                'email' => 'pak-eko979@example.com',
                'phone' => '000005761',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$lt3R2.q9qAUAJP6TJe6zkujtPBb3/6qH6Mjf./nhC7Zbj/DhOR5cy',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:09',
                'updated_at' => '2026-03-28 03:45:09',
            ],
            [
                'id' => 28,
                'nid' => 'DRV-1740',
                'name' => 'joe',
                'email' => 'joe459@example.com',
                'phone' => '000001860',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$cVC/24WVubAWhPz9GL1/QOXvLgqXcyAB26lUtvxTHamjjivTLq3Z.',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:15',
                'updated_at' => '2026-03-28 03:45:15',
            ],
            [
                'id' => 29,
                'nid' => 'DRV-8594',
                'name' => 'Nyoman Edi',
                'email' => 'nyoman-edi770@example.com',
                'phone' => '000001996',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$VXIt0WxQf9iB6uCrMZ2/yOb0cHD1XockxHkt5fR8rAR.dR1ygZMT2',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:16',
                'updated_at' => '2026-03-28 03:45:16',
            ],
            [
                'id' => 30,
                'nid' => 'DRV-5331',
                'name' => 'Nanank',
                'email' => 'nanank351@example.com',
                'phone' => '000003294',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$Z7Jsk3ORIJ8zcO78AmMoqOwHkfCOmocwnw.I7LVsD.CXn3Arw9/za',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:17',
                'updated_at' => '2026-03-28 03:45:17',
            ],
            [
                'id' => 31,
                'nid' => 'DRV-7672',
                'name' => 'Morsidin',
                'email' => 'morsidin519@example.com',
                'phone' => '000008013',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$3/.C0/.madvQHebnV36EPOFFepE8tATS8PIhFVZda/2xtqKEpJJg.',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:18',
                'updated_at' => '2026-03-28 03:45:18',
            ],
            [
                'id' => 32,
                'nid' => 'DRV-8016',
                'name' => 'Pak Wko',
                'email' => 'pak-wko860@example.com',
                'phone' => '000005505',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$JW0Zf4jg0jEWW0FxoQwxK.E90pKuSdlNayfVh6kby7DT2Nm1dqn32',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:45:31',
                'updated_at' => '2026-03-28 03:45:31',
            ],
            [
                'id' => 33,
                'nid' => 'DRV-5882',
                'name' => 'Gabriel',
                'email' => 'gabriel800@example.com',
                'phone' => '000009250',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$y8f/qvxr5kawgQxzcgAYaeL3sgFD0n3MQrnyk7eQVXn/F0g6UHAK2',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:28',
                'updated_at' => '2026-03-28 03:55:28',
            ],
            [
                'id' => 34,
                'nid' => 'DRV-7859',
                'name' => 'driver siluman',
                'email' => 'driver-siluman816@example.com',
                'phone' => '000005132',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$iKqNQZ.HQs.aGgzfBSswweA9747nGTzUSL7D8NdIujQ5r6iyJyYG2',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:32',
                'updated_at' => '2026-03-28 03:55:32',
            ],
            [
                'id' => 35,
                'nid' => 'DRV-6357',
                'name' => 'made budiana',
                'email' => 'made-budiana326@example.com',
                'phone' => '000009133',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$6YozdpkXrE9x3THyBHoWCer1kCWEMbrewnFlnXFcXAJJ5uF3X1GiW',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:33',
                'updated_at' => '2026-03-28 03:55:33',
            ],
            [
                'id' => 36,
                'nid' => 'DRV-2080',
                'name' => 'pak Eko cash',
                'email' => 'pak-eko-cash997@example.com',
                'phone' => '000001800',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$BAaPIBl/hnMgscV86JaSeu.QE4v4lwlg0gv1.95olinakIB0borDK',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:35',
                'updated_at' => '2026-03-28 03:55:35',
            ],
            [
                'id' => 37,
                'nid' => 'DRV-8188',
                'name' => 'Sofitel Bali Nusa Dua Beach Resort',
                'email' => 'sofitel-bali-nusa-dua-beach-resort272@example.com',
                'phone' => '000002824',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$5Z919NkleURhEb7kPtAaZe7Tn5Q6VSyEs0qsucnZ9VnYsNPakiYFe',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:39',
                'updated_at' => '2026-03-28 03:55:39',
            ],
            [
                'id' => 38,
                'nid' => 'DRV-6801',
                'name' => 'Tedyy',
                'email' => 'tedyy945@example.com',
                'phone' => '000002173',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$EWEbU6QV06XMgrVYhjbQb.Gy8gOb3l27VzFBoYbnkno79y36mIiba',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:40',
                'updated_at' => '2026-03-28 03:55:40',
            ],
            [
                'id' => 39,
                'nid' => 'DRV-4369',
                'name' => 'grab',
                'email' => 'grab528@example.com',
                'phone' => '000008783',
                'nik' => null,
                'nik_image' => null,
                'sim' => null,
                'sim_image' => null,
                'password' => '$2y$12$kXkf2FWQUFusK3Zathr8F.OWNc9vRM4Iy357Nzq7pFO.WdAFMdmfS',
                'image' => null,
                'status' => 'inactive',
                'created_at' => '2026-03-28 03:55:40',
                'updated_at' => '2026-03-28 03:55:40',
            ],
        ];

        DB::table('drivers')->insert($drivers);
    }
}
