services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siwride_app
    restart: unless-stopped
    ports:
      - "4444:8000"
      - "5173:5173"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql_8
      - DB_PORT=3306
      - DB_DATABASE=siwride
      - DB_USERNAME=root
      - DB_PASSWORD=putri123
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql_8
    networks:
      - siwride-network

  mysql_8:
    image: mysql:8.0
    container_name: mysql_8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=putri123
      - MYSQL_DATABASE=siwride
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - siwride-network

networks:
  siwride-network:
    driver: bridge

volumes:
  mysql-data:
